### PR TITLE
perf!: make yaml dependency optional

### PR DESCRIPTION
**Pull request by ArnaudBarre**
### `Notable Changes`

The direct `yaml` dependency is currently adding ~250kb to Vite bundle size for something that seems to be a very small usecase. I think it's better to make it a peer dependency and release a major 

#### `Commit Message Summary (CHANGELOG)`

```
Make `yaml` a peer dependency. If you are using a yaml configuration file, migrate to JSON or install `yaml` to your project
```

### `Type`

- [ ] CI
- [ ] Fix
- [x] Perf
- [ ] Docs
- [ ] Test
- [ ] Chore
- [ ] Style
- [ ] Build
- [ ] Feature
- [ ] Refactor

### `SemVer`

- [ ] Fix (:label: Patch)
- [ ] Feature (:label: Minor)
- [x] Breaking Change (:label: Major)

### `Checklist`

- [x] Lint and unit tests pass with my changes
- [x] I have added tests that prove my fix is effective/works
- [x] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes are merged and published in downstream modules

### CODE REVIEW

**Comment by ai** [comment]
Yes, I like the idea of reducing `node_modules` and I think it is a good way to do it.

But since it is breaking change, I need to think a little.

**Comment by ArnaudBarre** [comment]
Thanks for considering it! There is also a slight runtime perf benefit because node doesn't need to process the full `yaml` source code if you don't use it.

**Comment by ai** [comment]
Seems like there is only ≈100 `.postcssrc.yml` files around all public GitHub repos https://github.com/search?q=path%3A**%2F.postcssrc.yml&type=code&ref=advsearch

Not really popular config.

**Comment by ai** [comment]
Released in 6.0.

**Pull request merged**
